feat: component/Avatar
getsoss/k-project-FE pull request #5
Opened 2024-07-11 13:38 UTC by seowooda

# PR Type

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 패키지 의존성 변경, CI/CD, 환경 설정 등

# Overview

Avatar 컴포넌트 추가
imageUrl props를 받아 이미지가 있을 경우 해당 이미지를, 없을 경우 "CN"이라는 텍스트를 보여준다.

- todo

# Additional Comment
프로필 정보 변경 페이지에서 이미지를 바꿨을 때 컴포넌트가 제대로 불러와질지 확실하지 않음. 
해당 페이지 개발하면서 확인해야 할 것 같습니다.

# Issue

#XXX

# Check List

- [ ] 관련된 이슈를 연결하였나요?
- [x] 올바른 PR 컨벤션을 작성했나요?
- [x] 적절한 라벨을 선택했나요?
- [x] Assignee와 Reviewer를 설정했나요?

2024-07-11 14:24 UTC, hin6150 requested changes

2024-07-11 14:24 UTC, hin6150 commented on src/components/Avatar/Avatar.tsx
> +}
[P2] CN이라는 정적 텍스트를 보여주기보다 Props로 사용자 이름을 가져와서 축약하는건 어떨까요?
신홍기와 같은 경우, 홍기로 출력한다거나 Kevin Shin의 경우 KS으로 축약한다던가 ..

축약하는 함수를 만들어서 사용해보면 좋을 것 같아요 ~!

2024-07-11 14:25 UTC, hin6150 commented on src/components/Avatar/Avatar.tsx
> +}
[컨벤션](https://www.notion.so/KNU-24-2-K-7868fe4b01ab46d8bf24c8de735686b6?p=8c50bbe066e34913b04f3ac074134204&pm=s#ce4653dd018c43778b4c933bee86a0de)의 코드리뷰 문화를 참고해서 작성하고 있습니다!

2024-07-11 16:07 UTC, seowooda commented on src/components/Avatar/Avatar.tsx
> +}
> [P2] CN이라는 정적 텍스트를 보여주기보다 Props로 사용자 이름을 가져와서 축약하는건 어떨까요? 신홍기와 같은 경우, 홍기로 출력한다거나 Kevin Shin의 경우 KS으로 축약한다던가 ..
> 
> 축약하는 함수를 만들어서 사용해보면 좋을 것 같아요 ~!

해당 부분 추가했습니다!
한글 이름일 때 뒤에 두 글자 출력, 영어 이름일 경우 띄어쓰기 기준 대문자 출력으로 수정했습니다
ex) 이서우 -> 서우, Seowoo -> S, Seo Woo-> SW

2024-07-12 03:54 UTC, hin6150 approved these changes
고생하셨습니다!

2024-07-12 03:56 UTC, merged