feat: component/input
getsoss/k-project-FE pull request #6
Opened 2024-07-11 13:51 UTC by seowooda

# PR Type

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 패키지 의존성 변경, CI/CD, 환경 설정 등

# Overview

Input 컴포넌트 추가
label, id, type, placeholder, disabled를 props로 받고있습니다. 해당 컴포넌트를 불러올 때 필요한 props를 지정해주면 됩니다.

- todo
input focus css 수정

# Additional Comment

# Issue

피그마에서 border을 inside로 수정해두었다고 하셨는데 input창이 focus될 때의 css를 수정하지 못했다.

#XXX

# Check List

- [ ] 관련된 이슈를 연결하였나요?
- [x] 올바른 PR 컨벤션을 작성했나요?
- [x] 적절한 라벨을 선택했나요?
- [x] Assignee와 Reviewer를 설정했나요?

2024-07-11 14:44 UTC, hin6150 commented
[P3] "피그마에서 border을 inside로 수정해두었다고 하셨는데 input창이 focus될 때의 css를 수정하지 못했다."와 같은 경우에는 focus-visible css 속성을 제거해주면 될 것 같아요.
```
focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 
```
현재 focus-visbile으로 outline-none으로 되어있는데 ring-2, ring-ring가 외각에 나와있는 것 같아서 해당 요소를 지우고 focus:border-2 focus:border-2 focus:border-stale-400으로 적용해보면 어떨까요?

2024-07-11 14:48 UTC, hin6150 commented
[P4] 글꼴과 같은 경우는 저도 좀 더 조사해봐야해서..

관련자료
https://dev.to/algoorgoal/nextjs-tailwindcsse-pretendard-ponteu-jeogyonghagi-1g87

shadcn의 폰트 설정은 따라서 해두긴 했습니다(다른폰트 인것 같긴해요 ㅠㅠ)
https://ui.shadcn.com/docs/installation/next

2024-07-11 14:49 UTC, hin6150 requested changes
고생하셨습니다!

2024-07-12 01:50 UTC, seowooda commented
> [P2] "피그마에서 border을 inside로 수정해두었다고 하셨는데 input창이 focus될 때의 css를 수정하지 못했다."와 같은 경우에는 focus-visible css 속성을 제거해주면 될 것 같아요.
> 
> ```
> focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 
> ```
> 
> 현재 focus-visbile으로 outline-none으로 되어있는데 ring-2, ring-ring가 외각에 나와있는 것 같아서 해당 요소를 지우고 focus:border-2 focus:border-stale-400으로 적용해보면 어떨까요?
> 
> box-sizing: border-box도 적용하면 좋습니다!

저도 focus-visible을 계속 건들면서 해봤는데 여전히 focus가 이렇게 나타나네요ㅠ
해당 부분은 더 찾아봐야 할 것 같습니다.
![image](https://github.com/user-attachments/assets/4c6eb31a-2310-45f9-a56d-ba8890e6f11a)

2024-07-12 03:55 UTC, hin6150 approved these changes
고생하셨습니다!

2024-07-12 03:56 UTC, merged